name: Gold Price Bot

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  send-price:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python gold_bot.py
        env:
          GOLD_API_KEY: ${{ secrets.GOLD_API_KEY }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
